name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
    types: [opened, synchronize, reopened]

jobs:  
  build-test:
    # requires dependency from step above
    name: Test Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Set up archived Oracle JDK 17.0.3.1
      uses: oracle-actions/setup-java@v1
      with:
        website: oracle.com
        release: 17
        version: 17.0.3.1       
    - name: Maven build
      run: |
       echo "maven build - Clean test"
       mvn clean test
